# Configuración principal de la aplicación

# Mapeo de provincias a datasources (ESENCIAL para el RepositoryFactory)
provincia:
  mapping:
    "Buenos Aires": pba
    "Avellaneda": mda
    "La Pampa": santa-rosa
    "Chaco": chaco
    "Entre Ríos": entre-rios
    "Formosa": formosa

# Configuración de las bases de datos
spring:
  datasource:
    pba:
      url: ${PBA_URL:jdbc:postgresql://localhost:5432/pba_db}
      username: ${PBA_USERNAME:postgres}
      password: ${PBA_PASSWORD:password}
      driver-class-name: org.postgresql.Driver
    mda:
      url: ${MDA_URL:jdbc:postgresql://localhost:5432/mda_db}
      username: ${MDA_USERNAME:postgres}
      password: ${MDA_PASSWORD:password}
      driver-class-name: org.postgresql.Driver
    santa-rosa:
      url: ${SANTA_ROSA_URL:jdbc:postgresql://localhost:5432/santa_rosa_db}
      username: ${SANTA_ROSA_USERNAME:postgres}
      password: ${SANTA_ROSA_PASSWORD:password}
      driver-class-name: org.postgresql.Driver
    chaco:
      url: ${CHACO_URL:jdbc:postgresql://localhost:5432/chaco_db}
      username: ${CHACO_USERNAME:postgres}
      password: ${CHACO_PASSWORD:password}
      driver-class-name: org.postgresql.Driver
    entre-rios:
      url: ${ENTRE_RIOS_URL:jdbc:postgresql://localhost:5432/entre_rios_db}
      username: ${ENTRE_RIOS_USERNAME:postgres}
      password: ${ENTRE_RIOS_PASSWORD:password}
      driver-class-name: org.postgresql.Driver
    formosa:
      url: ${FORMOSA_URL:jdbc:postgresql://localhost:5432/formosa_db}
      username: ${FORMOSA_USERNAME:postgres}
      password: ${FORMOSA_PASSWORD:password}
      driver-class-name: org.postgresql.Driver

# Configuración de queries
queries:
  path: "classpath:queries/"
  files:
    - "consultar_personas_juridicas.sql"
    - "reporte_infracciones_detallado.sql"
    - "reporte_infracciones_general.sql"
    - "reporte_radar_fijo_por_equipo.sql"
    - "reporte_semaforo_por_equipo.sql"
    - "reporte_vehiculos_por_municipio.sql"
    - "reporte_sin_email_por_municipio.sql"
    - "verificar_imagenes_radar.sql"

# Deshabilitar Swagger/Springfox temporalmente
# Configuración de logging (opcional)
logging:
  level:
    org.transito_seguro: DEBUG
    org.springframework.jdbc: DEBUG