# Configuraciones BD

spring:
  datasource:
    pba:
      url: ${pba_url}
      username: ${pba_username}
      password: ${pba_password}
      driver-class-name: org.postgresql.Driver
    mda:
      url: ${mda_url}
      username: ${mda_username}
      password: ${mda_password}
      driver-class-name: org.postgresql.Driver
    santa_rosa:
      url: ${santa_rosa_url}
      username: ${santa_rosa_username}
      password: ${santa_rosa_password}
      driver-class-name: org.postgresql.Driver
    chaco:
      url: ${chaco_url}
      username: ${chaco_username}
      password: ${chaco_password}
      driver-class-name: org.postgresql.Driver
    entre_rios:
      url: ${entre_rios_url}
      username: ${entre_rios_username}
      password: ${entre_rios_password}
      driver-class-name: org.postgresql.Driver
    formosa:
      url: ${formosa_url}
      username: ${formosa_username}
      password: ${formosa_password}
      driver-class-name: org.postgresql.Driver